# Generated by Django 6.0.8 on 2026-08-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='الهوية الوطنية / الإقامة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
