# Generated by Django 6.0.8 on 2026-09-09 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_national_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_set_password',
            field=models.BooleanField(default=False, verbose_name='يجب تعيين كلمة مرور جديدة'),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('resolved', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عالجها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب استرجاع كلمة مرور',
                'verbose_name_plural': 'طلبات استرجاع كلمة المرور',
                'ordering': ['-requested_at'],
            },
        ),
    ]
