# Generated by Django 6.0.8 on 2026-08-27 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم البيئة')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'group_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'بيئة',
                'verbose_name_plural': 'البيئات',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles', models.PositiveIntegerField(default=0, verbose_name='الأميال')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='النقاط')),
                ('purchase_points', models.PositiveIntegerField(default=0, verbose_name='النقاط الشرائية')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم جوال ولي الأمر')),
                ('academic_stage', models.CharField(choices=[('grade_5', 'خامس ابتدائي'), ('grade_6', 'سادس ابتدائي'), ('grade_7', 'أول متوسط'), ('grade_8', 'ثاني متوسط'), ('grade_9', 'ثالث متوسط')], max_length=10, verbose_name='المرحلة الدراسية')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='participants.group', verbose_name='البيئة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
            },
        ),
    ]
