# Generated by Django 6.0.8 on 2026-08-29 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('attended', models.BooleanField(default=False, verbose_name='حضر؟')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_attendances', to='participants.participant', verbose_name='المشارك')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'group_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
            ],
            options={
                'verbose_name': 'حضور حلقة',
                'verbose_name_plural': 'حضور الحلقات',
                'constraints': [models.UniqueConstraint(fields=('participant', 'date'), name='unique_circle_attendance_per_day')],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(verbose_name='بداية الأسبوع')),
                ('attended', models.BooleanField(default=False, verbose_name='حضر؟')),
                ('is_early', models.BooleanField(default=False, verbose_name='حضور مبكر؟')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to='participants.participant', verbose_name='المشارك')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'group_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
            ],
            options={
                'verbose_name': 'حضور لقاء',
                'verbose_name_plural': 'حضور اللقاءات',
                'constraints': [models.UniqueConstraint(fields=('participant', 'week_start_date'), name='unique_meeting_attendance_per_week')],
            },
        ),
    ]
