# Generated by Django 6.0.8 on 2026-08-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_circleattendance_meetingattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['user__full_name'], 'verbose_name': 'مشارك', 'verbose_name_plural': 'المشاركون'},
        ),
    ]
