# Generated by Django 6.0.8 on 2026-09-01 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهمة')),
                ('description', models.TextField(verbose_name='وصف المهمة')),
                ('due_date', models.DateField(verbose_name='موعد التسليم')),
                ('allowed_formats', models.CharField(help_text='قائمة مفصولة بفواصل من: pdf, image, audio, video', max_length=100, verbose_name='الصيغ المسموحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'مهمة أسبوعية',
                'verbose_name_plural': 'المهام الأسبوعية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_submissions/%Y/%W/', verbose_name='الملف')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('accepted', 'مقبولة'), ('rejected', 'مرفوضة')], default='pending', max_length=10, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='participants.participant', verbose_name='المشارك')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='participants.weeklytask', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'تسليم مهمة',
                'verbose_name_plural': 'تسليمات المهام',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('task', 'participant'), name='unique_submission_per_task_per_participant')],
            },
        ),
    ]
