# Generated by Django 6.0.8 on 2026-09-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_weeklytask_tasksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='allowed_formats',
            field=models.CharField(choices=[('pdf', 'ملف PDF'), ('image', 'صورة'), ('audio', 'مقطع صوتي'), ('video', 'مقطع فيديو')], max_length=10, verbose_name='الصيغة المسموحة'),
        ),
    ]
