# Generated by Django 6.0.8 on 2026-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_weeklytask_allowed_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='reopened_for_resubmission',
            field=models.BooleanField(default=False, verbose_name='أُتيح للتسليم مجددًا'),
        ),
    ]
