# Generated by Django 6.0.8 on 2026-09-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_tasksubmission_reopened_for_resubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_products/', verbose_name='الصورة')),
                ('price', models.PositiveIntegerField(verbose_name='السعر (نقاط شرائية)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوفرة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_order', models.PositiveIntegerField(verbose_name='السعر وقت الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('refunded', 'مسترجَع')], default='pending', max_length=10, verbose_name='الحالة')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاسترجاع')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='participants.participant', verbose_name='المشارك')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='participants.storeproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-ordered_at'],
            },
        ),
    ]
