# Generated by Django 6.0.8 on 2026-09-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_storeproduct_storeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleattendance',
            name='achieved',
            field=models.BooleanField(default=False, verbose_name='إنجاز؟'),
        ),
    ]
