# Generated by Django 6.0.8 on 2026-09-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_circleattendance_achieved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsResetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_before_reset', models.PositiveIntegerField(verbose_name='النقاط قبل التصفير')),
                ('reset_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التصفير')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_snapshots', to='participants.participant', verbose_name='المشارك')),
                ('reset_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='نفّذه')),
            ],
            options={
                'verbose_name': 'لقطة نقاط قبل التصفير',
                'verbose_name_plural': 'لقطات نقاط قبل التصفير',
                'ordering': ['-reset_at', '-points_before_reset'],
            },
        ),
    ]
