# Generated by Django 6.0.8 on 2026-09-10 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_pointsresetsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='group',
            name='supervisor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'group_supervisor'}, to=settings.AUTH_USER_MODEL, verbose_name='المشرفون'),
        ),
    ]
