# Generated by Django 6.0.8 on 2026-09-12 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_remove_group_supervisor_group_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_delta', models.IntegerField(verbose_name='التغيير في النقاط')),
                ('source', models.CharField(choices=[('meeting_attendance', 'حضور اللقاء الأسبوعي'), ('quran_circle', 'الحلقة القرآنية'), ('weekly_task', 'المهمة الأسبوعية'), ('extra', 'نقاط إضافية')], max_length=20, verbose_name='المصدر')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مُنِح بواسطة')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger_entries', to='participants.participant', verbose_name='المشارك')),
            ],
            options={
                'verbose_name': 'سجل نقاط',
                'verbose_name_plural': 'سجل النقاط',
                'ordering': ['-created_at'],
            },
        ),
    ]
