# Generated by Django 6.0.8 on 2026-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_pointsledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='يظهر للمشارك عند رفض تسليمه', verbose_name='سبب الرفض'),
        ),
    ]
