# Generated by Django 6.0.8 on 2026-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0012_tasksubmission_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='مميزة'),
        ),
    ]
