# Generated by Django 6.0.8 on 2026-09-13 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_tasksubmission_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsledgerentry',
            name='source',
            field=models.CharField(choices=[('meeting_attendance', 'حضور اللقاء الأسبوعي'), ('quran_circle', 'الحلقة القرآنية'), ('weekly_task', 'المهمة الأسبوعية'), ('weekly_activity', 'فعالية الأسبوع'), ('extra', 'نقاط إضافية')], max_length=20, verbose_name='المصدر'),
        ),
        migrations.CreateModel(
            name='WeeklyActivityAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('attended', models.BooleanField(default=False, verbose_name='حاضر؟')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_activity_attendances', to='participants.participant', verbose_name='المشارك')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجّله')),
            ],
            options={
                'verbose_name': 'فعالية الأسبوع',
                'verbose_name_plural': 'فعاليات الأسبوع',
                'constraints': [models.UniqueConstraint(fields=('participant', 'date'), name='unique_weekly_activity_per_day')],
            },
        ),
    ]
