# Generated by Django 6.0.8 on 2026-09-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_alter_pointsledgerentry_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='text_content',
            field=models.TextField(blank=True, help_text='يُستخدم فقط عند اختيار صيغة (نص مباشر) للتسليم', verbose_name='المحتوى النصي'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_submissions/%Y/%W/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='allowed_formats',
            field=models.CharField(help_text='يمكن اختيار أكثر من صيغة، يكفي المشارك تقديم واحدة منها', max_length=50, verbose_name='الصيغ المسموحة'),
        ),
    ]
