# Generated by Django 6.0.8 on 2026-09-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0015_tasksubmission_text_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مهمة نشطة'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='allowed_formats',
            field=models.CharField(choices=[('pdf', 'ملف PDF'), ('image', 'صورة'), ('audio', 'مقطع صوتي'), ('video', 'مقطع فيديو'), ('text', 'نص مباشر'), ('image_text', 'صورة + نص'), ('pdf_text', 'PDF + نص')], max_length=20, verbose_name='الصيغة المطلوبة'),
        ),
    ]
