# Generated by Django 6.0.8 on 2026-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0016_weeklytask_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='require_all_formats',
            field=models.BooleanField(default=False, help_text='إذا كان مفعّلًا، يجب على الطالب تقديم كل الصيغ المختارة معًا. إذا كان معطّلًا، يكفي تقديم صيغة واحدة يختارها الطالب.', verbose_name='تتطلب كل الصيغ معًا (AND)'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='allowed_formats',
            field=models.CharField(help_text='قائمة مفصولة بفواصل من: pdf, image, audio, video, text', max_length=50, verbose_name='الصيغ المسموحة'),
        ),
    ]
